version: '3.7'

services:
  api:
    container_name: dev_api
    image: dev_api:latest
    build: ./services/api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: dev_db
    image: postgres:12-alpine
    volumes:
      - ~/volumes/tradingapp/dev/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

