version: '3.7'

services:
  nginx:
    container_name: prod_nginx
    build: ./services/nginx
    volumes:
      - ~/volumes/tradingapp/prod/api/static:/home/app/api/project/static
      - ~/volumes/tradingapp/prod/api/media:/home/app/api/project/media
    ports:
      - 1337:80
    networks:
      - prod_api_net
    depends_on:
      - api
  api:
    container_name: prod_api
    image: prod_api:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ~/volumes/tradingapp/prod/api/static:/home/app/api/project/static
      - ~/volumes/tradingapp/prod/api/media:/home/app/api/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    networks:
      - prod_api_net
      - prod_db_net
    depends_on:
      - db
  db:
    container_name: prod_db
    image: postgres:12-alpine
    volumes:
      - ~/volumes/tradingapp/prod/postgresql:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - prod_db_net

networks:
  prod_api_net:
  prod_db_net:

