version: '3.7'

services:
  api:
    container_name: dev_api
    image: dev_api:latest
    build: ./services/api
    command: python -m flask run --host 0.0.0.0 --port 5000
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    networks:
      - dev_api_net
      - dev_db_net
    depends_on:
      - db
  db:
    container_name: dev_db
    image: postgres:12-alpine
    volumes:
      - ~/volumes/tradingapp/dev/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    networks:
      - dev_db_net
  mail:
    container_name: dev_mail
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
  memcached:
    container_name: dev_cache
    image: "memcached:alpine"
    networks:
      - dev_api_net
  redis:
    container_name: dev_redis
    image: "redis:alpine"
    networks:
      - dev_api_net

networks:
  dev_api_net:
  dev_db_net:
